name: 'Deploy Docker Compose'
description: 'Deploys Docker Compose configuration via SSH.'

inputs:
  ssh-private-key:
    description: 'SSH private key'
    required: true

  ssh-host:
    description: 'SSH host'
    required: true

  ssh-user:
    description: 'SSH user'
    required: false
    default: 'root'

  docker-compose-profile:
    description: 'Docker Compose Profile'
    required: false
    default: ''

  docker-compose-env-file-path:
    description: 'Docker Compose .env File Path'
    required: false
    default: ''

  docker-compose-env-file-content:
    description: 'Docker Compose .env File Content'
    required: false
    default: ''

  ssh-clone:
    description: 'Clone Repository via SSH'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2

    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" > ~/.ssh/config
        echo "    StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Deploy Docker Compose
      shell: bash
      run: |
        ${{ github.action_path }}/deploy.sh \
          "${{ github.action_path }}" \
          "${{ github.sha }}" \
          "${{ inputs.ssh-user }}" \
          "${{ inputs.ssh-host }}" \
          "${{ github.server_url}}" \
          "${{ github.repository }}" \
          "${{ inputs.docker-compose-profile }}" \
          "${{ inputs.docker-compose-env-file-path }}" \
          "${{ inputs.docker-compose-env-file-content }}" \
          "${{ inputs.ssh-clone }}"
